package dev.isaacudy.udytils.postgres.codegen

import java.io.File
import java.util.Properties

/**
 * A custom SQL→Kotlin type mapping supplied by a consumer to extend (or
 * override) the built-in [TypeRegistry] defaults.
 *
 * [factoryTemplate] is an Exposed column-factory expression with placeholders:
 *   * `{name}`      — the SQL column name (always available)
 *   * `{precision}` / `{scale}` — for numeric/decimal types
 *   * `{length}`    — for varchar/char types
 *
 * e.g. for `numeric`: kotlinType = "BigDecimal",
 *      factoryTemplate = "decimal(\"{name}\", {precision}, {scale})",
 *      imports = ["java.math.BigDecimal"].
 */
data class TypeOverride(
    val kotlinType: String,
    val factoryTemplate: String,
    val imports: Set<String>,
)

/**
 * Everything the codegen engine needs for a single run, serialised by the
 * Gradle plugin to a `.properties` file whose path is the engine's only CLI
 * argument. Using java.util.Properties keeps the engine dependency-free.
 */
data class CodegenConfig(
    val migrationsDir: File,
    val schemaName: String,
    val excludedTables: Set<String>,
    // schema export
    val schemaSnapshotFile: File?,
    val schemaBanner: String,
    // table generation
    val generatedSourcesDir: File?,
    val outputPackage: String?,
    val columnTypesPackage: String,
    val tableSuffix: String,
    val rowSuffix: String,
    val rowNameOverrides: Map<String, String>,
    val sqlTypeOverrides: Map<String, TypeOverride>,
) {
    companion object {
        const val DEFAULT_SCHEMA = "public"
        const val DEFAULT_COLUMN_TYPES_PACKAGE = "dev.isaacudy.udytils.postgres"
        val DEFAULT_EXCLUDED_TABLES = setOf("flyway_schema_history")
        const val DEFAULT_BANNER =
            "Generated by the dev.isaacudy.udytils.postgres Gradle plugin. Do not edit by hand."

        fun load(propsFile: File): CodegenConfig {
            require(propsFile.isFile) { "Codegen properties file not found: ${propsFile.absolutePath}" }
            val props = Properties().apply { propsFile.inputStream().use { load(it) } }

            fun req(key: String): String =
                props.getProperty(key) ?: error("Missing required codegen property '$key'")

            fun opt(key: String, default: String): String =
                props.getProperty(key)?.takeIf { it.isNotBlank() } ?: default

            val rowNameOverrides = props.stringPropertyNames()
                .filter { it.startsWith("rowNameOverride.") }
                .associate { it.removePrefix("rowNameOverride.") to props.getProperty(it) }

            val sqlTypeOverrides = props.stringPropertyNames()
                .filter { it.startsWith("sqlTypeOverride.") }
                .associate { key ->
                    val sqlType = key.removePrefix("sqlTypeOverride.").lowercase()
                    // value form: kotlinType|factoryTemplate|comma,separated,imports
                    val parts = props.getProperty(key).split("|", limit = 3)
                    require(parts.size >= 2) {
                        "sqlTypeOverride for '$sqlType' must be 'kotlinType|factoryTemplate[|imports]'"
                    }
                    val imports = parts.getOrNull(2)
                        ?.split(",")
                        ?.map { it.trim() }
                        ?.filter { it.isNotEmpty() }
                        ?.toSet()
                        .orEmpty()
                    sqlType to TypeOverride(parts[0].trim(), parts[1].trim(), imports)
                }

            val excluded = opt("excludedTables", DEFAULT_EXCLUDED_TABLES.joinToString(","))
                .split(",")
                .map { it.trim() }
                .filter { it.isNotEmpty() }
                .toSet()

            return CodegenConfig(
                migrationsDir = File(req("migrationsDir")),
                schemaName = opt("schemaName", DEFAULT_SCHEMA),
                excludedTables = excluded,
                schemaSnapshotFile = props.getProperty("schemaSnapshotFile")?.let(::File),
                schemaBanner = opt("schemaBanner", DEFAULT_BANNER),
                generatedSourcesDir = props.getProperty("generatedSourcesDir")?.let(::File),
                outputPackage = props.getProperty("outputPackage")?.takeIf { it.isNotBlank() },
                columnTypesPackage = opt("columnTypesPackage", DEFAULT_COLUMN_TYPES_PACKAGE),
                tableSuffix = opt("tableSuffix", "Table"),
                rowSuffix = opt("rowSuffix", "Row"),
                rowNameOverrides = rowNameOverrides,
                sqlTypeOverrides = sqlTypeOverrides,
            )
        }
    }
}
