package dev.isaacudy.udytils.urpc.server

import dev.isaacudy.udytils.urpc.UrpcLogger
import dev.isaacudy.udytils.urpc.UrpcRoute
import io.ktor.server.routing.Route
import io.ktor.server.routing.route

/**
 * Mounts urpc's HTTP and WebSocket routes under [rootPath] and exposes a
 * [UrpcRoute] inside [block] for installing service implementations.
 *
 * ```
 * import com.example.api.install   // generated by KSP per @UrpcService
 *
 * application {
 *     routing {
 *         urpc(rootPath = "/api") {
 *             install(ChatServiceImpl(sessionAuth), ChatService::class)
 *             install(UserServiceImpl(...), UserService::class)
 *         }
 *     }
 * }
 * ```
 *
 * Each service ends up mounted at `${rootPath}/services/${descriptor.name}` for
 * unary calls and `${rootPath}/streamingServices/${descriptor.name}` for streams.
 *
 * The host is responsible for installing Ktor's `WebSockets` plugin separately if
 * any streaming services are registered.
 *
 * @param rootPath optional path prefix to mount everything under. Empty (the
 *  default) mounts at the routing root.
 * @param errorMapper maps handler exceptions to HTTP status codes (see
 *  [ServiceErrorMapper.Default]).
 * @param logger logging hook used for streaming error reporting.
 */
fun Route.urpc(
    rootPath: String = "",
    errorMapper: ServiceErrorMapper = ServiceErrorMapper.Default,
    logger: UrpcLogger = UrpcLogger.NoOp,
    block: UrpcRoute.() -> Unit,
) {
    if (rootPath.isEmpty()) {
        KtorUrpcRoute(this, errorMapper, logger).block()
    } else {
        route(rootPath) {
            KtorUrpcRoute(this, errorMapper, logger).block()
        }
    }
}
