package dev.isaacudy.udytils.architecture.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Classpath
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.net.URLClassLoader

/**
 * Generates the architecture test classes from the module's [ArchitectureDefinition]: the compiled
 * main classes are loaded reflectively, the definition's groups are read, and one `@TestFactory`
 * per group is emitted so the JUnit tree keeps the flat `<Name>Test › <Group> › <Construct> › <rule>`
 * shape. Because the sources are derived, nothing test-related is checked into source control.
 */
@CacheableTask
abstract class GenerateArchitectureTestsTask : DefaultTask() {

    /** Fully-qualified name of the consumer's `ArchitectureDefinition` object. */
    @get:Input
    abstract val definitionClass: Property<String>

    /** The module's main runtime classpath (compiled catalog + the architecture framework). */
    @get:Classpath
    abstract val definitionClasspath: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val fqn = definitionClass.get()
        val urls = definitionClasspath.files.map { it.toURI().toURL() }.toTypedArray()
        val source = URLClassLoader(urls, ClassLoader.getPlatformClassLoader()).use { loader ->
            val definition = Class.forName(fqn, true, loader).getField("INSTANCE").get(null)
            val groups = definition.javaClass.getMethod("getGroups").invoke(definition) as List<*>
            val groupIds = groups.map { it!!.javaClass.getMethod("getId").invoke(it) as String }
            val hasMembership = definition.javaClass.getMethod("getMembership").invoke(definition) != null
            render(fqn, groupIds, hasMembership)
        }

        val packagePath = fqn.substringBeforeLast('.').replace('.', '/')
        val out = outputDirectory.get().asFile.resolve(packagePath)
        outputDirectory.get().asFile.deleteRecursively()
        out.mkdirs()
        out.resolve("${fqn.substringAfterLast('.')}GeneratedTests.kt").writeText(source)
    }

    private fun render(fqn: String, groupIds: List<String>, hasMembership: Boolean): String {
        val packageName = fqn.substringBeforeLast('.')
        val name = fqn.substringAfterLast('.')
        return buildString {
            appendLine("// Generated by the dev.isaacudy.udytils.architecture Gradle plugin — do not edit.")
            appendLine("package $packageName")
            appendLine()
            appendLine("import dev.isaacudy.udytils.architecture.ArchitectureRun")
            appendLine("import dev.isaacudy.udytils.architecture.testing.ArchitectureDocsHarness")
            appendLine("import dev.isaacudy.udytils.architecture.testing.architectureGroupNodes")
            appendLine("import dev.isaacudy.udytils.architecture.testing.architectureMembershipNodes")
            appendLine("import dev.isaacudy.udytils.architecture.testing.assertCatalogSourcesRegistered")
            appendLine("import dev.isaacudy.udytils.architecture.testing.assertRunnerDetectsViolationsAndParsesGraph")
            appendLine("import org.junit.jupiter.api.DisplayName")
            appendLine("import org.junit.jupiter.api.DynamicNode")
            appendLine("import org.junit.jupiter.api.TestFactory")
            appendLine("import kotlin.test.Test")
            appendLine()
            appendLine("/** The architecture rules of [$name] — one nested test per rule, one factory per group. */")
            appendLine("class ${name}Test {")
            groupIds.forEach { groupId ->
                appendLine()
                appendLine("    @TestFactory")
                appendLine("    @DisplayName(\"$groupId\")")
                appendLine("    fun ${groupId.replaceFirstChar(Char::lowercase)}(): List<DynamicNode> = architectureGroupNodes(run, \"$groupId\")")
            }
            if (hasMembership) {
                appendLine()
                appendLine("    @TestFactory")
                appendLine("    @DisplayName(\"membership\")")
                appendLine("    fun membership(): List<DynamicNode> = architectureMembershipNodes(run)")
            }
            appendLine()
            appendLine("    companion object {")
            appendLine("        /** One Konsist scope + module-graph scan shared by every factory. */")
            appendLine("        private val run by lazy { ArchitectureRun($name) }")
            appendLine("    }")
            appendLine("}")
            appendLine()
            appendLine("/** Doc↔catalog sync for [$name]'s generated docs. */")
            appendLine("class ${name}DocsTest : ArchitectureDocsHarness($name)")
            appendLine()
            appendLine("/** Self-checks on the architecture-test machinery itself. */")
            appendLine("class ${name}IntegrityTest {")
            appendLine()
            appendLine("    @Test")
            appendLine("    fun runnerDetectsViolationsAndParsesGraph() = assertRunnerDetectsViolationsAndParsesGraph($name)")
            appendLine()
            appendLine("    @Test")
            appendLine("    fun everyDeclaredConstructAndGroupIsRegistered() = assertCatalogSourcesRegistered($name)")
            appendLine("}")
        }
    }
}
