package dev.isaacudy.udytils.urpc.client

import dev.isaacudy.udytils.urpc.UrpcClientFactory
import dev.isaacudy.udytils.urpc.UrpcClientInterceptor
import dev.isaacudy.udytils.urpc.UrpcLogger
import io.ktor.client.HttpClient
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob

/**
 * Returns a Ktor-backed [UrpcClientFactory] rooted at [baseUrl].
 *
 * ```
 * import com.example.api.create   // generated by KSP alongside the @Urpc interface
 *
 * val httpClient = HttpClient { install(WebSockets) }
 * val urpc = httpClient.urpcClient(
 *     baseUrl = "https://api.example.com",
 *     interceptors = listOf(bearerTokenInterceptor(authTokenFlow)),
 * )
 * val chat: ChatService = urpc.create()
 * ```
 *
 * Unary calls are HTTP POSTs to `${baseUrl}/services/${name}`; streaming and bidirectional calls
 * are **multiplexed over a single WebSocket** at `${baseUrl}/urpc`, opened lazily on first use and
 * reconnected with backoff if it drops.
 *
 * Auth, tracing and any other per-call concerns are expressed as [interceptors] (see
 * [bearerTokenInterceptor][dev.isaacudy.udytils.urpc.bearerTokenInterceptor] for the common
 * bearer-token case). An interceptor that suspends gates the call — so a logged-out client opens
 * no streaming connection until it is authenticated.
 *
 * @param baseUrl protocol + host + base path (e.g. `"https://api.example.com"`).
 * @param interceptors client interceptors run before each call to populate per-call metadata
 *  (which becomes request headers for unary calls and `Open`-frame metadata for streaming).
 * @param tokenRefresher invoked when a unary HTTP call returns 401; the call is retried once
 *  (re-running the interceptor chain) after the refresher completes.
 * @param logger logging hook for connection / reconnect / error messages.
 */
fun HttpClient.urpcClient(
    baseUrl: String,
    interceptors: List<UrpcClientInterceptor> = emptyList(),
    tokenRefresher: suspend () -> Unit = {},
    logger: UrpcLogger = UrpcLogger.NoOp,
): UrpcClientFactory = KtorUrpcClientFactory(
    httpClient = this,
    baseUrl = baseUrl,
    // The connection manager runs for the lifetime of the factory (typically an app-scoped
    // singleton). SupervisorJob so one failed connection attempt never tears the scope down.
    scope = CoroutineScope(SupervisorJob() + Dispatchers.Default),
    tokenRefresher = tokenRefresher,
    interceptors = interceptors,
    logger = logger,
)
