package dev.isaacudy.udytils.urpc.client

import dev.isaacudy.udytils.urpc.UrpcClientFactory
import dev.isaacudy.udytils.urpc.UrpcLogger
import io.ktor.client.HttpClient

/**
 * Returns a Ktor-backed [UrpcClientFactory] rooted at [baseUrl].
 *
 * ```
 * import com.example.api.create   // generated by KSP alongside the @UrpcService interface
 *
 * val httpClient = HttpClient { install(WebSockets) }
 * val urpc = httpClient.urpcClient("https://api.example.com")
 * val chat: ChatService = urpc.create(ChatService::class)
 * ```
 *
 * @param baseUrl protocol + host + base path (e.g. `"https://api.example.com"`).
 *  Service paths are appended as `${baseUrl}/services/${descriptor.name}` and
 *  WebSocket paths as `${baseUrl}/streamingServices/${descriptor.name}`.
 * @param authTokenProvider returns the bearer token to include on each request,
 *  or null for unauthenticated calls.
 * @param tokenRefresher invoked when an HTTP call returns 401; the call is
 *  retried once after the refresher completes.
 * @param logger logging hook used for streaming reconnect / error messages.
 */
fun HttpClient.urpcClient(
    baseUrl: String,
    authTokenProvider: () -> String? = { null },
    tokenRefresher: suspend () -> Unit = {},
    logger: UrpcLogger = UrpcLogger.NoOp,
): UrpcClientFactory = KtorUrpcClientFactory(
    httpClient = this,
    baseUrl = baseUrl,
    authTokenProvider = authTokenProvider,
    tokenRefresher = tokenRefresher,
    logger = logger,
)
