package dev.isaacudy.udytils.urpc.client.rest

import dev.isaacudy.udytils.urpc.UrpcClientFactory
import dev.isaacudy.udytils.urpc.UrpcLogger
import io.ktor.client.HttpClient

/**
 * Returns a [UrpcClientFactory] that serves KSP-generated urpc stubs from an existing JSON REST
 * API, so a client can be written against a urpc contract before the backend speaks urpc.
 *
 * ```
 * import com.example.api.create   // generated by KSP alongside the @Urpc interface
 *
 * val urpc = httpClient.restUrpcClient(
 *     baseUrl = "https://api.example.com",
 *     fallback = httpClient.urpcClient("https://api.example.com"),
 * ) {
 *     interceptors(bearerTokenInterceptor(authTokenFlow))
 *     tokenRefresher { auth.refresh() }
 *     service("userService") {
 *         headers("X-Api-Version" to "2")
 *         "getUser"    via get("/users/{id}")
 *         "listUsers"  via get("/users")
 *         "createUser" via post("/users")
 *         "updateUser" via put("/users/{id}")
 *         "deleteUser" via delete("/users/{id}")
 *         "search"     via post("/search") { response { it.jsonObject.getValue("data") } }
 *     }
 * }
 * val users: UserService = urpc.create()
 * ```
 *
 * The contract, the generated stubs and every call site are the same ones the native client
 * uses — only the transport differs. That is the point: as endpoints move to urpc, delete their
 * routes from this table one at a time and each falls through to [fallback]. When the table is
 * empty, delete the client and this dependency; nothing else changes.
 *
 * ### How a call is marshalled
 *
 * A call is routed by the descriptor's wire name (`"userService.getUser"`, i.e.
 * `@Urpc("userService")` plus the function name). The request is encoded to a JSON object with
 * [json][RestUrpcConfig.json], and then:
 *
 * 1. `{field}` placeholders in the path are filled from the matching request fields (primitives
 *    only, URL-encoded) and those fields are consumed;
 * 2. what's left becomes query parameters on `GET`/`DELETE` — repeating the name for an array,
 *    omitting nulls — or the JSON request body on `POST`/`PUT`/`PATCH`;
 * 3. a 2xx body is parsed, passed through the route's optional
 *    [response][RestRouteConfig.response] transform, and decoded with the contract's serializer;
 *    a `Unit` return ignores the body entirely.
 *
 * Anything that doesn't fit — a nested object in a query string, an envelope that needs more
 * than a transform, multipart, two calls behind one function — is what
 * [custom][RestServiceConfig.custom] is for.
 *
 * ### Parity with the native client
 *
 * [Interceptors][RestUrpcConfig.interceptors] run before every call and their metadata becomes
 * request headers; a 401 triggers [tokenRefresher][RestUrpcConfig.tokenRefresher] and exactly one
 * retry with the chain re-run; failures are decoded to
 * [ServiceException][dev.isaacudy.udytils.urpc.ServiceException] by default. Pass the same
 * interceptor list to both clients and auth, tracing and error handling behave identically on
 * either side of the migration.
 *
 * Streaming and bidirectional calls have no REST equivalent: unmapped ones are delegated to
 * [fallback], and one that *is* mapped to a REST route throws [UnsupportedOperationException].
 *
 * @param baseUrl protocol + host + base path (e.g. `"https://api.example.com"`); route paths are
 *  appended to it verbatim.
 * @param fallback handles every wire name the route table doesn't cover — normally the native
 *  [urpcClient][dev.isaacudy.udytils.urpc.client.urpcClient] pointed at the same backend. Without
 *  one, an unmapped call throws [RestUrpcException] naming the wire name and the configured
 *  service prefixes.
 * @param logger logging hook for fallback delegation and 401 retries.
 * @param configure declares the route table and the per-client settings; see [RestUrpcConfig].
 * @throws IllegalArgumentException if the table maps a wire name twice or a path template is
 *  malformed — both fail here, at construction, rather than on the call that uses them.
 */
fun HttpClient.restUrpcClient(
    baseUrl: String,
    fallback: UrpcClientFactory? = null,
    logger: UrpcLogger = UrpcLogger.NoOp,
    configure: RestUrpcConfig.() -> Unit,
): RestUrpcClientFactory = RestUrpcConfig().apply(configure).build(
    httpClient = this,
    baseUrl = baseUrl,
    fallback = fallback,
    logger = logger,
)
